name: Release to STG

on:
  push:
    branches:
      - main

jobs:
  Release-to-STG:
    runs-on: ubuntu-latest
    environment: STG

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          changed_packages=()
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Changed file ${changed_file}"
            #check if changed file is under "packages/" folder
            if [[ $changed_file == packages* ]]; then

              #extract packge name
              package_name=`sudo echo ${changed_file} | sed 's/packages\/\([^ \/]*\).*/\1/'`
              echo "Changed packaged ${package_name}"

              #if this is the first time we encountered this packge, we add it to the array
              match=0
              for old_pck in "${changed_packages[@]}"; do
                  if [[ old_pck = "package_name" ]]; then
                      match=1
                      break
                  fi
              done
              if [[ $match = 0 ]]; then
                  changed_packages+=($package_name)
              fi
            fi
          done
          echo "All values ${changed_packages[@]}"
        shell: bash