name: Release to Staging

on:
  push:
    branches:
      - main

jobs:
  Release-to-Staging:
    runs-on: ubuntu-latest
    environment: STG

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: files
        uses: jitterbit/get-changed-files@v1
        name: Retrieve all changed files from the push
      - id: changedPackages
        uses: nick-invision/retry@v2
        name: Find only changed packages
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            changed_packages=()
            for changed_file in ${{ steps.files.outputs.all }}; do
              echo "Changed file : $changed_file"
              #check if changed file is under "packages/" folder
              if [[ $changed_file == packages* ]]; then
                echo "It is package!"
                #extract packge name
                package_name=`sudo echo ${changed_file} | sed 's/packages\/\([^ \/]*\).*/\1/'`
                echo "Package name : $package_name"
                changed_packages+=($package_name)
              fi
            done
            echo $changed_packages
            dedup_changed_packages=( $(printf '%s\n' "${changed_packages[@]}" | sort -u) )
            echo $dedup_changed_packages
            echo "::set-output name=changed_packages::$dedup_changed_packages"
      - name: Check outputs
        shell: bash
        run: echo ${{ steps.changedPackages.outputs.changed_packages }}