name: Release to STG

on:
  push:
    branches:
      - main

jobs:
  Release-to-STG:
    runs-on: ubuntu-latest
    environment: STG

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: |
          git diff ./packages/phone-number-privacy
          git diff ./packages/attestation-service