name: Release to STG

on:
  push:
    branches:
      - main

jobs:
  Release-to-STG:
    runs-on: ubuntu-latest
    environment: STG

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          changed_packages=()
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "------------------------"
            echo "Changed file ${changed_file}"
            package_name=`sudo echo ${changed_file} | sed 's/packages\/\([^ ]*\)\/.*/\1/'`
            echo "Changed packaged ${package_name}"
          done
        shell: bash