name: Release to STG

on:
  push:
    branches:
      - main

jobs:
  Release-to-STG:
    runs-on: ubuntu-latest
    environment: STG

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          changed_packages = ()
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Changed file ${changed_file}"
            package_name = echo ${changed_file} | sed "s/^.*packages//\(.*\)//$/\1/"
            echo "Changed packaged ${package_name}"
          done