name: Release to all environments from STG

on:
  # Allows you to run this workflow manually ONLY
  workflow_dispatch:
    inputs:
      release-package:
        description: 'Which package should be released in the workflow'
        required: true
        default: 'none'

jobs:
  Release-to-Alfajores:
    runs-on: ubuntu-latest
    environment: ALFAJORES

    steps:
      - uses: actions/checkout@v2
      - run: ./packages/${{github.event.inputs.release-package}}/release/deployment.sh
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
  Test-Alfajores:
    environment: STG
    runs-on: ubuntu-latest
    needs: Release-to-Alfajores

    steps:
      - uses: actions/checkout@v2
      - run: ./packages/${{github.event.inputs.release-package}}/release/test.sh