name: Release to all environments from STG

on:
  # Allows you to run this workflow manually ONLY
  workflow_dispatch:
    inputs:
      release-package:
        description: 'Which package should be released in the workflow'
        required: true
        default: 'none'

jobs:
  Build-Packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ( cd packages/attestation-service/ && npm install)
        if: contains(github.event.inputs.release-package, 'attestation-service')
      - run: ( cd packages/phone-number-privacy/ && npm install)
        if: contains(github.event.inputs.release-package, 'phone-number-privacy')

  #Test and release to Alfajores
  Test-Alfajores:
    runs-on: ubuntu-latest
    needs: Build-Packages

    steps:
      - uses: actions/checkout@v2
      - run: ./packages/attestation-service/release/test.sh
        if: contains(github.event.inputs.release-package, 'attestation-service')
      - run: ./packages/phone-number-privacy/release/test.sh
        if: contains(github.event.inputs.release-package, 'phone-number-privacy')

  Release-to-Alfajores:
    runs-on: ubuntu-latest
    environment: ALFAJORES
    needs: Test-Alfajores

    steps:
      - uses: actions/checkout@v2
      - run: ./packages/attestation-service/release/release.sh
        if: contains(github.event.inputs.release-package, 'attestation-service')
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
      - run: ./packages/phone-number-privacy/release/release.sh
        if: contains(github.event.inputs.release-package, 'phone-number-privacy')
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}