name: Release to all environments from STG

on:
  # Allows you to run this workflow manually ONLY
  workflow_dispatch:
    inputs:
      release-package:
        description: 'Which package should be released in the workflow'
        required: true
        default: 'all'

jobs:
  #Test and release to Alfajores
  Test-Alfajores:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: ( cd packages/attestation-service/ && npm install && npm test) #TODO Extract to same test.sh 
        if: contains(github.event.inputs.release-package, 'attestation-service')

  Release-to-Alfajores:
    runs-on: ubuntu-latest
    environment: ALFAJORES
    needs: Test-Alfajores

    steps:
      - uses: actions/checkout@v2

      - run: echo "Release my attestation service with secret $ENV_SECRET"
        if: contains(github.event.inputs.release-package, 'attestation-service')
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}